version: '2'
services:
    bot-x-v2:
      build:
          context: ./
          dockerfile: dev.Dockerfile  # เปลี่ยน Dockerfile เป็น dev.Dockerfile
      ports:
          - "5050:5000"
      volumes:
          - ./:/code
      restart: always
      environment:
        - LISTEN_PORT=5000
        - UWSGI_INI=/code/uwsgi/uwsgi.ini
        - PYTHONPATH=/code/app
        - NGINX_WORKER_OPEN_FILES=20000
        - UWSGI_PROCESSES=1
        - UWSGI_CHEAPER=0
      env_file:
        - ./.env
